version: '3.0'

services:
  database:
    container_name: database
    image: postgres:bullseye
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
      - PGDATA=$PGDATA
    ports:
      - 5432:5432
    volumes:
      - ./mounts/database:/var/lib/postgresql/data
