version: '3.0'

services:

  database:
    container_name: database
    image: postgres:bullseye
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
      - PGDATA=$PGDATA
    ports:
      - 5432:5432
    volumes:
      - ./mounts/database:/var/lib/postgresql/data

  objs-storage:
    container_name: objs-storage
    image: minio/minio:RELEASE.2023-10-07T15-07-38Z
    restart: on-failure
    environment:
      - MINIO_ROOT_USER=$MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
      - MINIO_ADDRESS=$MINIO_ADDRESS
      - MINIO_CONSOLE_ADDRESS=$MINIO_CONSOLE_ADDRESS
    command: minio server /data
    volumes:
      - ./mounts/minio-data:/data
    ports:
      - 9000:9000
      - 9001:9001
